version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: "Asia/Shanghai"
      time: "09:00"
    target-branch: "dev"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      timezone: "Asia/Shanghai"
      time: "09:00"
    target-branch: "dev"
