version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: "Asia/Shanghai"
    target-branch: "dev"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      timezone: "Asia/Shanghai"
    target-branch: "dev"
