name: "WeCom (WeChat Work) Group Robot"
author: "Mean <390602272@qq.com>"
description: "Send a message through a WeCom group robot."
branding:
  icon: "message-circle"
  color: "green"
inputs:
  key:
    description: "机器人的key"
    required: true
  # 暂不支持图片和图文
  msgtype:
    description: "消息类型，支持文本（text）、markdown（markdown）、图片（image）、文件（file）"
    required: false
    default: "text"
  content:
    description: "消息内容，当消息类型为文件或图片时，content为文件名"
    required: true
outputs:
  errcode:
    description: "企业微信返回的errcode"
  errmsg:
    description: "企业微信返回的errmsg"
runs:
  using: "node16"
  main: "dist/index.js"
