name: 持续集成

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript 测试
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      LC_ALL: zh_CN.UTF-8

    steps:
      - name: 检出
        id: checkout
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: 设置 Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: 安装依赖
        id: pnpm-install
        run: pnpm install

      - name: 格式检查
        id: pnpm-format-check
        run: pnpm format:check

      - name: Lint
        id: pnpm-lint
        run: pnpm lint

      - name: 测试
        id: pnpm-ci-test
        run: pnpm ci-test
        env:
          TEST_KEY: ${{ secrets.TEST_KEY }}

  test-action:
    name: GitHub Actions 测试
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      LC_ALL: zh_CN.UTF-8

    steps:
      - name: 检出
        id: checkout
        uses: actions/checkout@v4

      - name: 测试本地 Action
        id: test-action
        uses: ./
        with:
          key: ${{ secrets.TEST_KEY }}
          content: 'test'

      - name: 打印输出
        id: output
        run: echo "${{ steps.test-action.outputs.errmsg }}"
